# Generated by Django 5.1.2 on 2024-11-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_bio_alter_profile_date_of_birth_and_more'),
        ('post', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='account.profile'),
        ),
    ]
