# Generated by Django 5.1.2 on 2025-01-28 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_tagnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='post.post')),
                ('tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_by', to=settings.AUTH_USER_MODEL)),
                ('user_tagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
