# Generated by Django 5.1.2 on 2025-01-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_usertagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertagged',
            options={'ordering': ['-created']},
        ),
    ]
