# Generated by Django 5.1.2 on 2025-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_usertagged_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertagged',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
