# Generated by Django 5.1.2 on 2025-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatgroupcurrentusercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroupcurrentusercount',
            name='connected_user_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
