# Generated by Django 5.1.2 on 2025-01-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatgroupcurrentusercount_connected_user_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroupCurrentUserCount',
        ),
    ]
